const $=id=>document.getElementById(id);
let game=null,busy=false;
function node(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
function controls(){const active=game?.status==='playing';$('new').disabled=busy;$('story').disabled=busy;$('send').disabled=busy||!active||!game.turns_left;$('question').disabled=busy||!active;$('hint').disabled=busy||!active||game.hints_used>=game.hints_available||!game.turns_left;$('reveal').disabled=busy||!active;$('send').textContent=busy?'主持人思考中…':'交给主持人 ↗';}
function render(data){game=data;$('game-title').textContent=game.title;$('game-surface').textContent=game.surface;$('status').textContent={playing:'谜局进行中',solved:'恭喜，你已经完全猜出答案了！',revealed:'已揭晓'}[game.status];$('count').textContent=game.questions;$('hints').textContent=game.hints_used;$('history').replaceChildren();for(const entry of game.history){const turn=node('div','','turn');turn.append(node('div',(entry.kind==='guess'?'我的还原：':'')+entry.text,'player'));const host=node('div','','host');host.append(node('strong',entry.answer),node('small',entry.kind==='hint'?'题库预设提示':`本地模型 · ${Math.round(entry.elapsed_ms)} ms`));turn.append(host);$('history').append(turn);}if(!game.history.length)$('history').append(node('p','一次问一个是非问题，逐步缩小可能性。','empty'));$('history').scrollTop=$('history').scrollHeight;$('solution-card').hidden=!game.solution;$('solution-title').textContent=game.status==='solved'?'你已经完全猜出答案了！':'汤底揭晓';$('solution').textContent=game.solution??'';const latest=[...game.history].reverse().find(h=>h.scores?.length);$('scores').replaceChildren();$('latency').textContent=latest?Math.round(latest.elapsed_ms):'—';if(latest){for(const score of latest.scores){const row=node('div'),head=node('div','','score-head');head.append(node('span',score.name),node('span',(score.probability*100).toFixed(1)+'%'));const bar=node('div','','bar'),fill=node('i');fill.style.width=score.probability*100+'%';bar.append(fill);row.append(head,bar);$('scores').append(row);}}else $('scores').textContent='等待提问。';controls();}
async function post(path,body){const response=await fetch('/api/turtle/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:'内容长度或格式不符合要求');return data;}
async function perform(fn){if(busy)return;busy=true;$('error').textContent='';controls();try{await fn();}catch(error){$('error').textContent=error.message;}finally{busy=false;controls();}}
$('story').onchange=()=>$('custom').hidden=$('story').value!=='custom';
$('new').onclick=()=>perform(async()=>{const custom=$('story').value==='custom';const payload={story_id:$('story').value};if(custom){payload.title=$('title').value;payload.surface=$('surface').value;payload.solution=$('solution-input').value;if(!payload.surface.trim()||!payload.solution.trim())throw Error('请先填写汤面和汤底。');}const data=await post('new',payload);render(data);$('question').value='';if(custom){$('title').value='';$('surface').value='';$('solution-input').value='';$('custom').hidden=true;$('story').value='random';} });
$('ask-form').onsubmit=e=>{e.preventDefault();const text=$('question').value.trim();if(!text)return;perform(async()=>{render(await post(game.id+'/turn',{kind:document.querySelector('[name=kind]:checked').value,text}));$('question').value='';});};
$('hint').onclick=()=>perform(async()=>render(await post(game.id+'/turn',{kind:'hint'})));
$('reveal').onclick=()=>{if(!confirm('确定揭晓汤底吗？本局将结束。'))return;perform(async()=>render(await post(game.id+'/turn',{kind:'reveal'})));};
async function init(){try{const response=await fetch('/api/turtle/stories');if(!response.ok)throw Error('题库读取失败');for(const story of await response.json()){const option=node('option',story.title+' · '+story.level);option.value=story.id;$('story').append(option);}}catch(e){$('error').textContent=e.message;}controls();}init();
